# Generated by Django 4.2.1 on 2023-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='comm',
            field=models.IntegerField(default=0),
        ),
    ]
